matrix:
    include:
       - language: julia
         julia: 1.0
         os: osx
notifications:
    email: false
after_success:
    - julia -e 'VERSION>=v"0.7-"&&using Pkg; cd(Pkg.dir("Cairo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
